# ReminderBot Pro - Production Environment
# Generated by Terraform - DO NOT EDIT MANUALLY

DATABASE_URL="${database_url}"
REDIS_URL="${redis_url}"
SECRET_KEY="${secret_key}"
ENVIRONMENT="${environment}"
FRONTEND_URL="https://${domain_name}"
CORS_ORIGINS="https://${domain_name}"
SERVER_NAME="${domain_name}"
LOG_LEVEL=info
